spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog_user?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&autoReconnectForPools=true&allowMultiQueries=true&serverTimezone=UTC
    password: 12345678
    username: root

mybatis:
  mapper-locations: classpath*:mapper/*.xml
mapper:
  mappers: com.cloud.blog.tkmybatis.mybatisconfig.MyMapper
